# Generated by Django 4.0 on 2021-12-27 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libManager', '0004_bookrecords_copies_tot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecords',
            name='curr_issuers',
            field=models.ManyToManyField(related_name='%(class)s_curr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrecords',
            name='prev_issuers',
            field=models.ManyToManyField(related_name='%(class)s_prev', to=settings.AUTH_USER_MODEL),
        ),
    ]
