# Generated by Django 4.0 on 2021-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books_issued_curr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='dues',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='issue_limit',
            field=models.IntegerField(default=5),
        ),
    ]
